### ISSUE TITLE
Error during "Create New Project"

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-server#44]
Trying to create a project for a dataset on the desktop web-interface for Strabo. The only required field is Project Name, and I have filled that in. Get the following error:

Fatal error: Uncaught GraphAware\Neo4j\Client\Exception\Neo4jException: Invalid input 'd': expected 'n/N' or 's/S' (line 1, column 41 (offset: 40)) "MATCH (from), (to) where id(from)= and id(to)=3836 CREATE UNIQUE (from)-[r:HAS_PROJECT]->(to) return id(r)" ^ in /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php:122 Stack trace: #0 /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Client.php(64): GraphAware\Neo4j\Client\Connection\Connection->run('MATCH (from), (...', Array, NULL) #1 /opt/www/ezneo4j.php(249): GraphAware\Neo4j\Client\Client->run('MATCH (from), (...') #2 /opt/www/new_project.php(131): ezneo4j->addRelationship('', 3836, 'HAS_PROJECT') #3 {main} thrown in /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php on line 122

**Comment by zmichels** [comment]
Huh. Tried 3 times... worked third time.
